api:
  version: 1.0.0
  title: Mesa de ayuda API
  basePackage: com.enyoi.apimesaayuda
  description: Api para aplicacion Mesa de ayuda
  terms: https://

#Server configurations
server:
  servlet:
    context-path: /api-mesa-ayuda
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

#Swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs

#Spring configs
spring:
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    #jdbc:mysql://enyoi.co:3306/enyoi_db
    #enyoi_db
    #3tT9ip9_8
    url: jdbc:mysql://enyoi.co:3306/enyoi_db
    username: enyoi_db
    password: 3tT9ip9_8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: jaderdavidv@gmail.com
    password: f e k d v l w w w x p o t t a y
    properties:
      mail:
        smtp:
          connectiontimeout: 25000
          timeout: 25000
          writetimeout: 25000
          auth: true
          starttls:
            required: true
            enable: true

#Token Configs
jwt:
  secret: Ap1M3544yud@
  expiration: 3600000